name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Use main.lambda.ts as main.ts
        run: |
          if [ -f src/main.lambda.ts ]; then
            mv src/main.lambda.ts src/main.ts
          else
            echo "Warning: src/main.lambda.ts not found, skipping rename."
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Install dependencies
        run: npm ci

      - name: Replace bcrypt with bcryptjs
        run: |
          find . -type f \( -name "*.js" -o -name "*.ts" -o -name "package.json" -o -name "package-lock.json" \) -print0 | xargs -0 -r sed -i 's/\bbcrypt\b/bcryptjs/g'

      - name: Build the project
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir -p lambda_package
          cp -r dist/ lambda_package/
          cp package.json package-lock.json lambda_package/
          cd lambda_package
          npm install --omit=dev
          zip -r ../deploy.zip .

      - name: Deploy to AWS Lambda
        run: |
          RETRY_COUNT=5
          RETRY_INTERVAL=10
          
          for i in $(seq 1 $RETRY_COUNT); do
            aws lambda update-function-code \
              --function-name arn:aws:lambda:us-east-1:557690620729:function:lambda-webhook-coolfix \
              --zip-file fileb://deploy.zip && break
            if [ "$i" -eq "$RETRY_COUNT" ]; then
              echo "Max retries reached. Exiting."
              exit 1
            fi
            echo "Retrying in $RETRY_INTERVAL seconds..."
            sleep $RETRY_INTERVAL
          done

      - name: Update Lambda function configuration
        run: |
          RETRY_COUNT=5
          RETRY_INTERVAL=10
          
          for i in $(seq 1 $RETRY_COUNT); do
            aws lambda update-function-configuration \
              --function-name arn:aws:lambda:us-east-1:557690620729:function:lambda-webhook-coolfix \
              --handler dist/src/main.handler && break
            if [ "$i" -eq "$RETRY_COUNT" ]; then
              echo "Max retries reached. Exiting."
              exit 1
            fi
            echo "Retrying in $RETRY_INTERVAL seconds..."
            sleep $RETRY_INTERVAL
          done
